### ISSUE TITLE
Bool defined in tidyPlatform.h conflicts with Swift Bool

### ISSUE THREAD

**Issue by starrynight** [htacg/SwLibTidy#2]
Once SwLibTidy is imported, the enum Bool defined tidyPlatform.h becomes the default Bool.
All my existing Bool become illegal unless renamed to Swift.Bool.  It's a bit less ideal to affect an existing project to that level

I've taken a look at the source and it seems you're doing the same thing to circumvent this issue.  Just wonder if this is a temporary fix or there is a better way? Or would it be possilbe for the tidy developer to consider rename the enum to something like TidyBool?

**Comment by balthisar** [comment]
I'll look for another workaround. Tidy has been using Bool since the dawn of time, and in C interop, it's completely compatible, i.e., it's mapped one:one. Swift is the oddball here.

One suggestion in the meantime: this is a "lower-level" library with top level functions, and it pretty much wraps LibTidy procedurally. The original intention (and still major to-do list item) is to further wrap this with a lightweight set of classes that might avoid having to import the C header in the first place.

I agree, you shouldn't be forced to prefix everything with Swift.

**Comment by starrynight** [comment]
Thanks a lot for the feedback. I'll try to wrap a few functions myself for the time being. It's still good to see the original project is revitalized and is even brought to Swift. 
Hope to see the higher level Swift wrapper soon!
